[package]
name = "gcd"
version = "0.1.0"
edition = "2021"
authors = ["Tibor Kircsi <tkircsi@gmail.com>"]
description = "Calculates the greatest common divisor of the given numbers"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
